spring:
  kafka:
    streams:
      application-id: fraud-detector
      bootstrap-servers: localhost:9092
      default:
        key:
          serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        value:
          serde: org.apache.kafka.common.serialization.Serdes$JsonSerde
