spring.cloud.stream:
  function:
    bindings:
      fraudDetector-in-0: transactions
      fraudDetector-out-0: fraud-alerts
  bindings:
    transactions:
      destination: transactions
    fraud-alerts:
      destination: fraud-alerts

fraud-detector:
  fraud:
    threshold: 100000
spring:
  cloud:
    function:
      definition: fraudDetector

    stream:
      kafka:
        streams:
          binder:
            deserialization-exception-handler: logandcontinue