spring.cloud.stream:
  function:
    bindings:
      fraudDetector-in-0: transactions
      fraudDetector-out-0: fraud-alerts
  bindings:
    transactions:
      destination: transactions
      content-type: application/json
    fraud-alerts:
      destination: fraud-alerts
      content-type: application/json

fraud-detector:
  fraud:
    threshold: 100000